name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: package-version
    attributes:
      label: Package
      description: What version of the linode_api4 package are you using?
      placeholder: 5.3.0
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: List any custom configurations and the steps to reproduce this error

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: If you received an error output that is too long, use Gists