name: Help
description: You're pretty sure it's not a bug but you can't figure out why it's not working
title: "[Help]: "
labels: ["help wanted"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What are you attempting to do, what error messages are you getting?
    validations:
      required: true