name: Nightly Smoke Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  smoke_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: pip install -U setuptools wheel boto3 certifi

      - name: Install Python SDK
        run: make dev-install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run smoke tests
        run: |
          make smoketest
        env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
