name: Nightly Smoke Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      sha:
        description: 'Commit SHA to test'
        required: false
        default: ''
        type: string


jobs:
  smoke_tests:
    if: github.repository == 'linode/linode_api4-python' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: pip install -U setuptools wheel boto3 certifi

      - name: Install Python SDK
        run: make dev-install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run smoke tests
        id: smoke_tests
        run: |
          make smoketest
        env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "*Nightly Smoke Tests Completed*",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Nightly Smoke Tests Completed*\n\n*Build Result:* ${{ steps.smoke_tests.outcome == 'success' && 'Build Passed' || 'Build Failed' }}\n\n*Job Details:*\n- Workflow: ${{ github.workflow }}\n- Branch: `${{ github.ref_name }}`\n- Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n- Commit: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|`${{ github.sha }}`>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

