name: release
on:
  workflow_dispatch: null
  release:
    types: [ published ]
jobs:
  pypi-release:
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    runs-on: ubuntu-latest
    environment: pypi-release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: pip install -U wheel build certifi

      - name: Build the package
        run: make build
        env:
          LINODE_SDK_VERSION: ${{ github.event.release.tag_name }}

      - name: Publish the release artifacts to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # pin@release/v1.12.4
