name: Notify Dev DX Channel on Release
on:
  release:
    workflow_dispatch: null
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack - Main Message
        id: main_message
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "New Release Published: *<${{ github.event.release.html_url }}|${{ github.repository }} - ${{ github.event.release.tag_name }}>* is now live! :tada:"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Slack - Threaded Release Notes
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "thread_ts": "${{ steps.main_message.outputs.ts }}",
              "text": "Release Notes:\n${{ toJSON(github.event.release.body) }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
